language: python
cache: pip
dist: xenial
matrix:
    fast_finish: true
    include:
      - { python: "3.6", env: DJANGO=2.2 }
      - { python: "3.6", env: DJANGO=3.0 }
      - { python: "3.6", env: DJANGO=3.1 }

      - { python: "3.7", env: DJANGO=2.2 }
      - { python: "3.7", env: DJANGO=3.0 }
      - { python: "3.7", env: DJANGO=3.1 }

      - { python: "3.8", env: DJANGO=2.2 }
      - { python: "3.8", env: DJANGO=3.0 }
      - { python: "3.8", env: DJANGO=3.1 }

      - { python: "3.9", env: DJANGO=2.2 }
      - { python: "3.9", env: DJANGO=3.0 }
      - { python: "3.9", env: DJANGO=3.1 }
install:
    - pip install tox tox-venv tox-travis
    - curl -sSL https://raw.githubusercontent.com/sdispater/poetry/master/get-poetry.py | python -
    - source $HOME/.poetry/env
script:
    - tox
after_success:
    - pip install codecov
    - codecov -e TOXENV,DJANGO
notifications:
    email: false